# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16.0-browsers

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
      # - run:
      #     name: Do `yarn install` on cache miss
      #     command: |
      #       if [ -d "./node_modules" ]; then
      #         echo "Restored node_modules from cache";
      #       else
      #         echo "Fill node_modules via yarn install";
      #         yarn install --frozen-lockfile
      #       fi
      # seems we always need to run yarn for mono repos to get nested dependencies and bin links

      - run: yarn install --frozen-lockfile
  
      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ checksum "yarn.lock" }}

      # build what needs to be build so we can use it in the next steps
      - run: npm run build

      # auto build typescript definition files (not part of build as locally JsDoc alone is all we need)
      - run: npm run build:types

      - run: npm run test:bs

      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  test-deploy:
    jobs: [test]
